### ISSUE TITLE
Hacer diagrama de la arquitectura actual

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/herramienta-resiliencia-servidor#7]
# Descripción
Hacer un diagrama con la arquitectura especifica actual (contenedores, tecnologías, etc).

Luego Daniel envía esto a las personas de ecopetrol, idealmente esta semana,

**Comment by danflop** [comment]
https://app.diagrams.net/#G1IDfBBdYzgsYk2k7HliUQIW8_7OupdGIp
